name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: first-step
          run: echo "hello action"
    second_job:
        runs-on: ubuntu-latest
        needs: first_job
        steps:
        - name: first-step
          run: echo "hello action"
